name: flutter_notebook_10th_story
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  polygon_clipper: ^1.0.2
  sliding_up_panel: any
  badges: any
  date_picker_timeline: any
  google_nav_bar: any
  line_icons: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
